services:
  mongodb:
    image: mongo:latest
    container_name: mongo_travel
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: travel-db
    volumes:
      - mongodb_travel_data:/data/db

volumes:
  mongodb_travel_data:
